// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCoi80IGuqab4X8i1BsTkrQv02Nq-8kSM',
    appId: '1:103009173711:android:cc7be0baafa10cbf1637ba',
    messagingSenderId: '103009173711',
    projectId: 'monawpaty',
    storageBucket: 'monawpaty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM1SBPsiBh9ZyEC3xin6uve3GGMgteUbc',
    appId: '1:103009173711:ios:cd1a720a8e6767331637ba',
    messagingSenderId: '103009173711',
    projectId: 'monawpaty',
    storageBucket: 'monawpaty.appspot.com',
    androidClientId: '103009173711-m6h9g70uvr8l8kq0ph30j7g53nsomqh2.apps.googleusercontent.com',
    iosClientId: '103009173711-kdhjp0grcfm22d4me5na9fi8d636dk48.apps.googleusercontent.com',
    iosBundleId: 'com.shk.monawpaty.monawpaty',
  );
}
